# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/phoenix/anaconda3/bin/cmake

# The command to remove a file.
RM = /home/phoenix/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phoenix/CS/compiler/SimPascal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phoenix/CS/compiler/SimPascal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/phoenix/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/phoenix/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phoenix/CS/compiler/SimPascal/CMakeFiles /home/phoenix/CS/compiler/SimPascal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phoenix/CS/compiler/SimPascal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

generator/CodeGenerator.o: generator/CodeGenerator.cpp.o

.PHONY : generator/CodeGenerator.o

# target to build an object file
generator/CodeGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/CodeGenerator.cpp.o
.PHONY : generator/CodeGenerator.cpp.o

generator/CodeGenerator.i: generator/CodeGenerator.cpp.i

.PHONY : generator/CodeGenerator.i

# target to preprocess a source file
generator/CodeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/CodeGenerator.cpp.i
.PHONY : generator/CodeGenerator.cpp.i

generator/CodeGenerator.s: generator/CodeGenerator.cpp.s

.PHONY : generator/CodeGenerator.s

# target to generate assembly for a file
generator/CodeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/CodeGenerator.cpp.s
.PHONY : generator/CodeGenerator.cpp.s

generator/genConstType.o: generator/genConstType.cpp.o

.PHONY : generator/genConstType.o

# target to build an object file
generator/genConstType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genConstType.cpp.o
.PHONY : generator/genConstType.cpp.o

generator/genConstType.i: generator/genConstType.cpp.i

.PHONY : generator/genConstType.i

# target to preprocess a source file
generator/genConstType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genConstType.cpp.i
.PHONY : generator/genConstType.cpp.i

generator/genConstType.s: generator/genConstType.cpp.s

.PHONY : generator/genConstType.s

# target to generate assembly for a file
generator/genConstType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genConstType.cpp.s
.PHONY : generator/genConstType.cpp.s

generator/genExp.o: generator/genExp.cpp.o

.PHONY : generator/genExp.o

# target to build an object file
generator/genExp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genExp.cpp.o
.PHONY : generator/genExp.cpp.o

generator/genExp.i: generator/genExp.cpp.i

.PHONY : generator/genExp.i

# target to preprocess a source file
generator/genExp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genExp.cpp.i
.PHONY : generator/genExp.cpp.i

generator/genExp.s: generator/genExp.cpp.s

.PHONY : generator/genExp.s

# target to generate assembly for a file
generator/genExp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genExp.cpp.s
.PHONY : generator/genExp.cpp.s

generator/genFunc.o: generator/genFunc.cpp.o

.PHONY : generator/genFunc.o

# target to build an object file
generator/genFunc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genFunc.cpp.o
.PHONY : generator/genFunc.cpp.o

generator/genFunc.i: generator/genFunc.cpp.i

.PHONY : generator/genFunc.i

# target to preprocess a source file
generator/genFunc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genFunc.cpp.i
.PHONY : generator/genFunc.cpp.i

generator/genFunc.s: generator/genFunc.cpp.s

.PHONY : generator/genFunc.s

# target to generate assembly for a file
generator/genFunc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genFunc.cpp.s
.PHONY : generator/genFunc.cpp.s

generator/genProgram.o: generator/genProgram.cpp.o

.PHONY : generator/genProgram.o

# target to build an object file
generator/genProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genProgram.cpp.o
.PHONY : generator/genProgram.cpp.o

generator/genProgram.i: generator/genProgram.cpp.i

.PHONY : generator/genProgram.i

# target to preprocess a source file
generator/genProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genProgram.cpp.i
.PHONY : generator/genProgram.cpp.i

generator/genProgram.s: generator/genProgram.cpp.s

.PHONY : generator/genProgram.s

# target to generate assembly for a file
generator/genProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genProgram.cpp.s
.PHONY : generator/genProgram.cpp.s

generator/genStmt.o: generator/genStmt.cpp.o

.PHONY : generator/genStmt.o

# target to build an object file
generator/genStmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genStmt.cpp.o
.PHONY : generator/genStmt.cpp.o

generator/genStmt.i: generator/genStmt.cpp.i

.PHONY : generator/genStmt.i

# target to preprocess a source file
generator/genStmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genStmt.cpp.i
.PHONY : generator/genStmt.cpp.i

generator/genStmt.s: generator/genStmt.cpp.s

.PHONY : generator/genStmt.s

# target to generate assembly for a file
generator/genStmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/generator/genStmt.cpp.s
.PHONY : generator/genStmt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... intrinsics_gen"
	@echo "... compiler"
	@echo "... generator/CodeGenerator.o"
	@echo "... generator/CodeGenerator.i"
	@echo "... generator/CodeGenerator.s"
	@echo "... generator/genConstType.o"
	@echo "... generator/genConstType.i"
	@echo "... generator/genConstType.s"
	@echo "... generator/genExp.o"
	@echo "... generator/genExp.i"
	@echo "... generator/genExp.s"
	@echo "... generator/genFunc.o"
	@echo "... generator/genFunc.i"
	@echo "... generator/genFunc.s"
	@echo "... generator/genProgram.o"
	@echo "... generator/genProgram.i"
	@echo "... generator/genProgram.s"
	@echo "... generator/genStmt.o"
	@echo "... generator/genStmt.i"
	@echo "... generator/genStmt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

